server:
  port: 8090

spring:
  data:
    mongodb:
      database: security
      uri: mongodb://mongoadmin:mongoadmin@localhost:27017/
      password: mongoadmin
      username: mongoadmin
      authentication-database: admin
  application:
    name: spring-security-demo

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    enabled: true

token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855