server:
  port: 8090

spring:
  data:
    mongodb:
      database: security
      uri: mongodb://mongoadmin:mongoadmin@localhost:27017/
      password: mongoadmin
      username: mongoadmin
      authentication-database: admin
  application:
    name: spring-security-demo

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    enabled: true
